let prompt1 = 'asdfasdf';

let prop_output = `1. A firefighter helmet: As John exits his home, he grabs his firefighter helmet to show that he is a firefighter reporting for duty.
 
2. A jacket with the fire department emblem: John wears a jacket with the fire department's emblem on the back, indicating his profession and destination.

3. A walkie-talkie: John carries a walkie-talkie with him, which he uses to communicate with his fellow firefighters at the station as he heads out.

4. A key ring with multiple keys: As he locks his front door, John fumbles with a key ring that has keys for his home and the fire station, emphasizing his responsibility within the fire department.

5. A personal photo or memento: Before leaving his home, John takes a quick glance at a family photo or meaningful memento that serves as his motivation and a reminder of the importance of his job as a firefighter.`

const prop_regex = /[1-9]. /

const prop_lst = prop_output.replaceAll("\n","").split(prop_regex).shift()

const set_design_output = "1. Suburban Neighborhood Set: The scene is set in a peaceful suburban neighborhood with tree-lined streets and well-manicured lawns. John's house is a modest, one-story ranch-style home with a neatly landscaped front yard. As John exits the front door, he waves to his neighbors and picks up the daily newspaper from his front porch. The camera follows him as he gets into his firefighter's SUV parked in the driveway, turns on his flashing lights, and drives away, heading towards the fire station.\n\n2. Downtown Apartment Set: John lives in a charming multi-story brick apartment building situated in a bustling downtown area. The scene starts with John stepping out of his building's front entrance onto the busy sidewalk, greeted by the sounds of car horns and pedestrians chatting. He squeezes past a group of people waiting at a bus stop, gives a friendly nod to the local coffee shop owner, and then unlocks his parked firefighter's SUV to head to the fire station.\n\n3. Rustic Small-Town Set: This scene is set in a quaint and picturesque small town with historic buildings and cobblestone streets. John's house is a charming, restored Victorian-style home with an inviting front porch. As he steps out, he is warmly greeted by his neighbor walking their dog down the sidewalk. The camera pans out as John gets into his vintage red pickup truck with firefighter's equipment in the back and drives off, giving the audience a view of the idyllic main street leading to the fire station.\n\n4. Coastal Village Set: John lives in a cozy cottage by the sea, surrounded by other small, colorful homes in a tight-knit coastal village. The scene begins with a shot of the sun rising over the ocean, setting the backdrop for the day ahead. As John exits his home, he breathes in the fresh ocean air and greets a group of fishermen passing by with their catch of the day. He jumps into his firefighter's SUV adorned with surfboards on the roof and drives off, with the fire station located just a short distance away along the picturesque coastline.\n\n5. Modern Urban Set: John's home is in a contemporary high-rise apartment building with a view of the city skyline. The scene starts with a sweeping shot of the cityscape, zeroing in on John's building. As he steps out of the glass-fronted entrance, he's surrounded by the hustle and bustle of city life, with people commuting to work via bikes, buses, and taxis. John crosses the busy street amidst the morning rush hour, hops into his sleek firefighter's SUV parked on the curb, and drives off towards the state-of-the-art fire station located in the heart of the city."

const makeup_output = "1. The Everyday Hero: For John, a makeup look that focuses on his profession as a firefighter could be ideal for this scene. This style would involve subtle earthy tones on the eyes and face, accentuating his features without overdoing it, highlighting his strong, determined, and rugged appearance. A light layer of sweat or dirt might also be added to emphasize his line of work.\n\n2. The Clean-Cut Professional: This makeup look would showcase John as perfectly groomed, with neatly trimmed facial hair and flawless skin. The focus would be on creating a polished, professional appearance for his role as a firefighter, using natural makeup colors and avoiding heavy or extremely noticeable cosmetics.\n\n3. The Tired Morning: To add more depth to the character, John could be portrayed with a slightly tired and worn appearance, as if he just woke up or struggled to get some sleep the night before. This makeup style would involve adding subtle under-eye bags, darker shadowing around the eyes, and perhaps even a hint of redness or irritation.\n\n4. The Off-Duty Casual: Opt for a makeup style that presents John as laid-back, with a casual, off-duty appearance. Go for minimal or no makeup, adding just a touch of color for a healthy glow. Follow up with a light dusting of bronzer to accentuate his features or give the impression of a fresh tan.\n\n5. The True-to-Life Firefighter: This makeup style aims to highlight the realistic aspects of being a firefighter, with every detail enhancing the authenticity of his portrayal. For John, this style could include makeup to mimic minor bruises, cuts, or burns acquired from previous fires, along with a hint of soot or dirt on his face to show that he's always ready to jump into action. The makeup would be subtle but powerful, showing John as the capable, devoted firefighter he is."

const visual_effects_output = `1. Smoke and flames: To emphasize the danger and urgency of John's job as a firefighter, the scene could feature smoke and flames in the background or as part of the transition to the fire station. This would give the audience a sense of the risks involved in John's work.
2. Slow motion: The scene could be shot in slow motion to emphasize the importance of John's job and create a sense of drama and importance as he makes his way to work. This would give the audience a chance to appreciate the details of the scene and the character's movements.
3. Timelapse: Alternatively, the scene could be shot using timelapse photography to give the audience a sense of the passing of time and John's daily routine. This would emphasize the routine and repetition of his work.
4. Drone shots: A drone could be used to capture aerial shots of John as he exits his home and makes his way to the fire station, giving the audience a unique perspective and creating a sense of scope and grandeur.
5. Light and color effects: To create a visual theme for the movie, the scene could be enhanced with specific lighting and color effects. For example, the colors of the sunrise or sunset could be used to create a warm, inviting atmosphere, or harsh, red and orange colors could be used to emphasize the danger of the job
`

const lighting_output= "1. Golden hour lighting: The scene is set during sunrise, with warm, golden light enveloping John and his house, as he leaves his home for work. This soft and vibrant lighting sets a positive and energetic tone, emphasizing John's dedication and enthusiasm for his job at the Fire Station.\n\n2. Overcast lighting: As John exits his home, the sky is filled with soft, diffused light due to heavy cloud cover. This type of lighting creates a neutral and even-toned atmosphere, potentially representing an ordinary, routine day in John's life as a firefighter.\n\n3. Dappled sunlight: As John walks out of his house, bright shafts of sunlight pierce through the foliage of trees near his house, creating a dappled lighting effect on the ground and John himself. This type of lighting can provide visual interest and a sense of peace to the scene, as nature beautifully mingles with John's morning routine.\n\n4. Backlit silhouette: As John steps out of his house, the dominant light source comes from behind him, creating a dramatic silhouette effect. The backlighting emphasizes the outline and shape of John and can be seen as a metaphor for the bravery and strength he demonstrates in his firefighting career.\n\n5. Blue hour lighting: The scene takes place during the early morning hours before sunrise, also known as the blue hour. The sky is filled with deep blue hues that cast cool, gentle light on John and his surroundings. This tranquil and serene lighting sets a calm mood, allowing the audience to reflect on John's commitment to his work at the Fire Station amidst a peaceful dawn."

export {set_design_output, makeup_output, visual_effects_output, lighting_output}